version: "3.4"

services:
  xaler-ui:
    container_name: xaler-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

networks:
  default:
    external:
      name: xaler-net

